# Copyright (c) The Infra Company
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: local
    hooks:
      - id: gofumpt
        name: gofumpt
        entry: bash -c 'make fmt'
        language: system
        types: ["go"]
        files: main.go|cmd\/.*|internal\/.*
        pass_filenames: false
